#!/usr/bin/env bash
# Regenerate the pinned benchmark config from the CURRENT fusion.yaml.
#
# Run this after ANY edit to fusion.yaml that you want the blind run to measure.
# The bench deliberately reads a frozen snapshot, not fusion.yaml itself, so a
# run stays reproducible while you keep editing the live config — but that also
# means an edit you forget to snapshot is an edit the benchmark never sees.
#
#   ./bench/make-blind-config.sh
#   FUSION_CONFIG=./bench/blind-2026-08-21.yaml node node_modules/tsx/dist/cli.mjs src/index.ts
#
# Three deltas from fusion.yaml, all of them harness concerns, not product ones:
#
#  1. port 8088 — so the run never touches the live proxy on 8081.
#  2. the `ollama-lexus` account is dropped. Its api_key_env (OLLAMA_API_KEY_2)
#     is unset, so on failover it answers 401 and the connector pool goes fully
#     down for `connector_cooldown_s` (60s). One transient upstream 503 then
#     blackholes every proxy condition for a minute while the solo conditions,
#     which call the provider directly, retry and succeed. Set OLLAMA_API_KEY_2
#     in .env and this delta stops being necessary.
#  3. `fusion-coder-noweb` is added — fusion-coder with web grounding off. The
#     solo conditions get no web context, so without this clone the comparison
#     partly measures Tavily instead of the panel/judge/synth mechanism.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="bench/blind-2026-08-21.yaml"

python3 - "$OUT" <<'PY'
import sys

out = sys.argv[1]
src = open("fusion.yaml", encoding="utf-8").read()

if "  port: 8081" not in src:
    sys.exit("fusion.yaml no longer has `  port: 8081` — check the server block before trusting this script")
src = src.replace("  port: 8081", "  port: 8088", 1)

acct = "      - id: ollama-lexus\n        api_key_env: OLLAMA_API_KEY_2\n"
if acct in src:
    src = src.replace(acct, "")
else:
    print("note: keyless ollama-lexus account not found — nothing to drop")

if "fusion-coder:" not in src:
    sys.exit("fusion.yaml has no `fusion-coder:` model — the noweb clone below would not match it")

src += """
  # BENCH-ONLY (generated by bench/make-blind-config.sh, do not edit by hand).
  # fusion-coder with web grounding OFF: the like-for-like test of what the
  # panel/judge/synth mechanism contributes when the baselines see the same
  # information it does. The gap to `fusion` is what Tavily contributes.
  #
  # KEEP IN SYNC with fusion-coder above by hand — this clone is literal text,
  # so a panel/judge/synth change in fusion.yaml does NOT propagate here.
  fusion-coder-noweb:
    strategy: fusion
    panel: [ kimi-k2.7-code, deepseek-v4-pro:0813-cloud, glm-5.2 ]
    judge: deepseek-v4-flash
    synth: glm-5.2
    tool_mode: deliberate
    synth_request_overrides:
      reasoning_effort: "none"
    fusion_planning_turn_only: true
    web_search:
      enabled: false
"""

open(out, "w", encoding="utf-8").write(src)
print(f"wrote {out}")
PY

echo
echo "Panel/judge/synth in the snapshot — verify the noweb clone still matches fusion-coder:"
grep -nE "panel:|judge:|synth:|fusion_planning_turn_only:|enabled:" "$OUT" | sed 's/^/  /'
